title: Winding Tree
author: Maksim Izmaylov
email: max@windingtree.com
description: Decentralized Travel Distribution
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://windingtree.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: windingtree
github_username: windingtree
google_analytics_tracking_id: UA-101898971-1

# Build settings
destination: build
markdown: kramdown
sass:
  sass_dir: css/includes
  style: expanded
  deploy_style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME

# Defaults
defaults:
  name: Winding Tree
  title: Winding Tree &mdash; Decentralized Travel Distribution
